#!/usr/bin/env python3
"""
build_html.py

Gzips index.html and outputs a C header (index_html.h) containing a PROGMEM byte array.
Run this script whenever index.html is modified.
"""

import gzip
import os
import sys

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    html_path = os.path.join(script_dir, "index.html")
    
    # Target output in ac_controller directory or script dir
    out_dir = os.path.join(script_dir, "ac_controller")
    if not os.path.exists(out_dir):
        out_dir = script_dir
    out_path = os.path.join(out_dir, "index_html.h")

    if not os.path.isfile(html_path):
        print(f"Error: {html_path} not found!", file=sys.stderr)
        sys.exit(1)

    with open(html_path, "rb") as f:
        html_bytes = f.read()

    orig_len = len(html_bytes)
    gz_bytes = gzip.compress(html_bytes, compresslevel=9)
    gz_len = len(gz_bytes)

    lines = []
    lines.append("// Auto-generated by build_html.py. Do not edit manually.")
    lines.append("#ifndef INDEX_HTML_H_")
    lines.append("#define INDEX_HTML_H_\n")
    lines.append("#include <Arduino.h>\n")
    lines.append(f"// Original size: {orig_len} bytes, Gzipped: {gz_len} bytes ({gz_len / orig_len * 100:.1f}%)")
    lines.append(f"const uint32_t index_html_gz_len = {gz_len};\n")
    lines.append("const uint8_t index_html_gz[] PROGMEM = {")

    chunk_size = 16
    for i in range(0, gz_len, chunk_size):
        chunk = gz_bytes[i:i + chunk_size]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        if i + chunk_size < gz_len:
            lines.append(f"  {hex_vals},")
        else:
            lines.append(f"  {hex_vals}")

    lines.append("};\n")
    lines.append("#endif  // INDEX_HTML_H_\n")

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Successfully generated {out_path}")
    print(f"HTML size: {orig_len:,} bytes -> Gzip size: {gz_len:,} bytes ({gz_len / orig_len * 100:.1f}%)")

if __name__ == "__main__":
    main()
