; PlatformIO Project Configuration File for ESP32-C3 AC Controller

[platformio]
src_dir = ac_controller
include_dir = ac_controller

[env:esp32-c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

; USB CDC On Boot and USB Serial settings for ESP32-C3 Super Mini
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

; OTA partition scheme (Two 1.9MB app partitions for Over-The-Air updates)
board_build.partitions = min_spiffs.csv

lib_deps = 
    crankyoldgit/IRremoteESP8266 @ ^2.8.6
    bblanchon/ArduinoJson @ ^7.0.0

; To upload over Wi-Fi after first USB flash:
; upload_protocol = espota
; upload_port = ac.local
